

export const WordBank = {
    DEFAULT: 1,
    EXTENDED: 2,
};

export const GameMode = {
    EASY: 1,
    HARD: 2,
    LENIENT: 3, 
    EXTRA_HARD: 4, 
};

export const GuessStatus = {
    VALID: 'VALID',
    ERR_LENGTH: 'ERR_LENGTH',
    ERR_PREV: 'ERR_PREV',
    ERR_LETTER_RESTRICT: 'ERR_LETTER_RESTRICT',
    ERR_LETTER_GAURANTEE: 'ERR_LETTER_GAURANTEE',
    ERR_SPECIFIC_RESTRICT_1: 'ERR_SPECIFIC_RESTRICT_1',
    ERR_SPECIFIC_RESTRICT_2: 'ERR_SPECIFIC_RESTRICT_2',
    ERR_GRAYS: 'ERR_GRAYS',
    ERR_GREENS: 'ERR_GREENS',
    ERR_YELLOWS_CONTRADICT: 'ERR_YELLOWS_CONTRADICT',
    ERR_YELLOWS_MISSING: 'ERR_YELLOWS_MISSING',
    WORD_NOT_FOUND: 'WORD_NOT_FOUND',
    MONGODB_QUERY_FAILED: 'MONGODB_QUERY_FAILED',
    REDIS_QUERY_FAILED: 'REDIS_QUERY_FAILED',
};

export const QueryStatus = {
    VALID: 'VALID',
    ERR_LENGTH: 'ERR_LENGTH',
    ERR_LETTER_GUARANTEE_TOO_LARGE: 'ERR_LETTER_GUARANTEE_TOO_LARGE',
    ERR_LETTER_RESTRICT_SPECIFIC: 'ERR_LETTER_RESTRICT_SPECIFIC',
    ERR_LETTER_RESTRICT_GUARANTEE: 'ERR_LETTER_RESTRICT_GUARANTEE',
    ERR_LETTER_GUARANTEE_SPECIFIC: 'ERR_LETTER_GUARANTEE_SPECIFIC',
    NO_WORDS_FOUND: 'NO_WORDS_FOUND',
    NO_WORDS_FOUND_THEMATIC: 'NO_WORDS_FOUND_THEMATIC',
    LLM_REQUEST_FAILED: 'LLM_REQUEST_FAILED',
    ERR_OFFLINE_THEME: 'ERR_OFFLINE_THEME',
    MONGODB_QUERY_FAILED: 'MONGODB_QUERY_FAILED',
    REDIS_QUERY_FAILED: 'REDIS_QUERY_FAILED',
};

export const ContainedStatus = {
    VALID: 'VALID',
    MONGODB_QUERY_FAILED: 'MONGODB_QUERY_FAILED',
    REDIS_QUERY_FAILED: 'REDIS_QUERY_FAILED',
    ERR_NO_MONGOOSE_MODEL: 'ERR_NO_MONGOOSE_MODEL', 
};

export const LetterResult = {
    GREEN: 'green',
    YELLOW: 'yellow',
    GRAY: 'gray',
    WHITE: 'white', 
};
